### ISSUE TITLE
Wrong email displayed on notification settings of a single project

### ISSUE THREAD

**Issue by NobbZ** [hexfaktor/hex_faktor_web#10]
Maybe even wrong email is used for notifications, can't tell right now, since I gained access today and all my deps are up to date ;) Anyway, if it is used, I'll never get that notification emails.

A picture tells more than a thousand words:

![wrongemail](https://cloud.githubusercontent.com/assets/58951/13527116/131244b0-e20d-11e5-903e-a1abc57c2ba7.jpg)

When I click on the "change" link behind, my account settings appear with my already verified gmail-address in the form.

**Comment by rrrene** [comment]
That is one embarassingly stupid mistake. :disappointed_relieved: Your supsicion is correct: This is only a display problem, because I hardcoded my own email address while designing the screen :grin: 

Fixed it :+1:
