### ISSUE TITLE
Longer version numbers do not display correctly

### ISSUE THREAD

**Issue by lpil** [hexfaktor/hex_faktor_web#11]
<img width="900" alt="screen shot 2016-03-18 at 16 54 49" src="https://cloud.githubusercontent.com/assets/6134406/13885440/4fe13bd0-ed2a-11e5-88e1-0de2d8ac391d.png">

Should say `3.0.0-beta.2`

**Comment by rrrene** [comment]
Good catch :+1:

**Comment by fazibear** [comment]
Lastes version is `2.0.1`. `mix hex.outdated` report right value.

**Comment by rrrene** [comment]
@fazibear yes, you are right. I created a separate issue! :+1:
