### ISSUE TITLE
Notifications are not marked as read when their link is clicked on

### ISSUE THREAD

**Issue by lpil** [hexfaktor/hex_faktor_web#14]
Hello!

I expect a notification to be marked as read and dismissed when I click on the link it provides, as I will have then seen the content of the event that triggered the notification.

**Comment by rrrene** [comment]
:+1: That is definitely the expected behaviour. I will have a look when home why it is not working!

**Comment by rrrene** [comment]
@lpil I completely missed this issue after ElixirConf. Sorry for that. Fixed now! :shipit:
