### ISSUE TITLE
email address not extracted from github prevents confirmation

### ISSUE THREAD

**Issue by kipcole9** [hexfaktor/hex_faktor_web#20]
Signed up this morning and authorised through github.  Sync with github was fine.  However no confirmation email was received.  Went to resend confirmation and notices that there is no email address in the resend box.  Forcing resent results in an internal server error.  Presumably because no email address was retrieved from Github.

**Comment by rrrene** [comment]
@kipcole9 Thx for reporting! :+1: I will investigate the Internal Server Error!

The reason there is no email in your account is because you do not share your email publically (and HexFaktor only requests public information for your account).

**Comment by kipcole9** [comment]
I assumed that when github asked my to grant email scope to hexfaktor that I was granting it access irrespective of what my profile permissions say (its been so long I have no idea what I'm actually sharing)! 

Perhaps a short note before redirecting to github for authorisation that returning the email address is dependent not only on the oauth2 grant, but also on permissions?

Thanks for building hexfaktor too, much appreciated.

**Comment by rrrene** [comment]
> Perhaps a short note before redirecting to github for authorisation that returning the email address is dependent not only on the oauth2 grant, but also on permissions?

You are right. HexFaktor should do a better job of informing the user that he/she needs to add an email, if none could be retrieved from GitHub.

I am currently on a trop and will add this as soon as I return home!
