### ISSUE TITLE
Unable to add my repo

### ISSUE THREAD

**Issue by vintikzzz** [hexfaktor/hex_faktor_web#23]
Syncing my repo causes error `Build failed! Something went wrong ...`
https://beta.hexfaktor.org/github/vintikzzz/cassandra_ecto

**Comment by ahamez** [comment]
The same here, for the repo ahamez/protox (https://beta.hexfaktor.org/github/ahamez/protox).

**Comment by vertexclique** [comment]
@rrrene Seems like this issue causes to fail fast for every new repo?

**Comment by rrrene** [comment]
Yeah,  sorry for the late response. Will fix as soon as I get home! :+1:

**Comment by vintikzzz** [comment]
It works! Thanx!
