### ISSUE TITLE
Never got verification email, attempting to resend produced an error.

### ISSUE THREAD

**Issue by beckler** [hexfaktor/hex_faktor_web#24]
![screen shot 2017-01-30 at 12 32 25 pm](https://cloud.githubusercontent.com/assets/3254069/22433963/4192d044-e6e8-11e6-8c74-e19f4a97d010.png)

**Comment by beckler** [comment]
Ah, I just realized that Hexfaktor never pulled my email address from Github.
Manually adding my email address fixed the issue, and I received the verification email.

**Comment by rrrene** [comment]
@beckler I think HexFaktor only pulls public email adresses, since that is the scope it requests from GitHub. Glad you got it working! :+1:
