### ISSUE TITLE
Builds aren't working?

### ISSUE THREAD

**Issue by doughsay** [hexfaktor/hex_faktor_web#26]
Just added a new project to HexFaktor and it never gets any status updates; no badge is ever generated.  It seems like builds are being generated, but the `revision`, `status`, and `duration` columns are empty for all of them.

https://beta.hexfaktor.org/github/doughsay/maxwell_request_id

**Comment by rrrene** [comment]
This was fixed a while ago. Sorry for not closing the issue at the time and thx for the bug report! :+1:

**Comment by moski** [comment]
It's the same for me, i've added a new project yesterday and i don't see any data. https://beta.hexfaktor.org/github/moski/mojaz-io-api

**Comment by rrrene** [comment]
@moski I fixed the new hiccup. It's not getting any easier to maintain this 😢 

If you want to try an alternative to HexFaktor check out https://versioneye.com - they have Elixir support now!
