### ISSUE TITLE
Builds are failing

### ISSUE THREAD

**Issue by slashrsm** [hexfaktor/hex_faktor_web#27]
I added a [new repo](https://github.com/slashrsm/rasstaggregator) to the HexFactor. When I press the refresh button to get the results I see a progress bar which seems to be cloning the repo in the background which almost immediately shows the following message:

![screenshot-2017-4-28 hexfaktor](https://cloud.githubusercontent.com/assets/376889/25521085/a02afd9c-2bfe-11e7-9c8b-d477fc10398b.png)

I was trying to see if I could get any more information about the error, but it doesn't seem to be available.

**Comment by rrrene** [comment]
This was fixed a while ago. Sorry for not closing the issue at the time and thx for the bug report! :+1:

**Comment by slashrsm** [comment]
Works like a charm now. Thanks!
