### ISSUE TITLE
"Monitored" link does not work

### ISSUE THREAD

**Issue by lpil** [hexfaktor/hex_faktor_web#28]
![screen shot 2017-05-16 at 09 12 47](https://cloud.githubusercontent.com/assets/6134406/26096054/dbc034e0-3a17-11e7-9fa4-9d20ea053d1d.png)

Clicking the "Monitored" link on the center left doesn't take me to a list of monitored projects.

The URL it goes to is https://beta.hexfaktor.org/projects?filter=

**Comment by rrrene** [comment]
The link is correct. As far as I can tell, none of your projects are monitored. There the hint is displayed instead of an empty list (so you can take action).

Is there a misunderstanding re: the word "monitored" here?

**Comment by lpil** [comment]
I would expect to see an empty list if there's nothing in that filter? :)
