### ISSUE TITLE
Email notifications about projects not marked as monitored

### ISSUE THREAD

**Issue by lpil** [hexfaktor/hex_faktor_web#29]
Hello!

I'm getting emails about lpil/fawkes, a project that isn't monitored.

Cheers,
Louis

**Comment by lpil** [comment]
Still getting these unsolicited emails.

**Comment by rrrene** [comment]
Mmmh, maybe this a not-so-well-designed part of HexFaktor.

Could you do me a favor and disable the notifications for `lpil/fawkes`.

Here is an example from one of my libraries: 

![image](https://cloud.githubusercontent.com/assets/311914/26285542/5a5a3268-3e52-11e7-8aaa-2a29c47351ca.png)

By disabling these checkboxes, you should be good.

Please report if it does help :+1:

**Comment by lpil** [comment]
Thank you!

**Comment by lpil** [comment]
When I uncheck the boxes and hit save it re-checks them :(

**Comment by rrrene** [comment]
That's bad ... and a bug. One cannot uncheck all branches.

You should be able to uncheck the "Enable e-mail summaries for this project" checkbox and submit the form. That should do the trick.
