### ISSUE TITLE
Space between "top" and "level" ?

### ISSUE THREAD

**Issue by lpil** [hexfaktor/hex_faktor_web#4]
![screen shot 2016-02-15 at 08 54 27](https://cloud.githubusercontent.com/assets/6134406/13043731/c759efae-d3c1-11e5-980f-f7489120fc29.png)

**Comment by rrrene** [comment]
Thanks for reporting :+1:

**Comment by rrrene** [comment]
Changed "toplevel" to "top-level"! :+1:

**Comment by lpil** [comment]
:dancer:
