### ISSUE TITLE
Email verification results in error

### ISSUE THREAD

**Issue by jnbt** [hexfaktor/hex_faktor_web#5]
I've just tried to confirm my email, but received an error when opening the verification link:

> Could not verify your e-mail. Did you click on an old verification mail?

Because of reasons I don't want to publish the actual verification link, but the token ends with `[...]NlUDw`.

**Comment by rrrene** [comment]
This one should be fixed now. Can you verify?

**Comment by jnbt** [comment]
Works like a charm! 

![hexfaktor 2016-02-16 09-38-19](https://cloud.githubusercontent.com/assets/678542/13071030/1160191e-d491-11e5-9689-2d1cb0ff0d91.png)

**Comment by rrrene** [comment]
Great!
