### ISSUE TITLE
Use local timestamps for build history

### ISSUE THREAD

**Issue by jnbt** [hexfaktor/hex_faktor_web#7]
I expect local timestamps for the entries in the build history. Perhaps HexFaktor is already using local timestamps, but in this case the time is -1 hour for me.

E.g. https://beta.hexfaktor.org/projects/1623/settings?section=history

![hexfaktor 2016-02-15 14-06-05](https://cloud.githubusercontent.com/assets/678542/13049445/483b0fd8-d3ed-11e5-8346-744f2ee29510.png)

The builds where around 13:00 UTC, but 14:00 local time.

**Comment by rrrene** [comment]
:+1: We're now using relative time difference ("X minutes ago" or "Y days ago").
