### ISSUE TITLE
Rebuild webhook results in a 404

### ISSUE THREAD

**Issue by splattael** [hexfaktor/hex_faktor_web#8]
The installed webhook https://beta.hexfaktor.org/rebuild fails resulting in a 404.

Project: https://github.com/splattael/sfsobject

**Comment by rrrene** [comment]
Classical case of "that probably never worked" :disappointed: 

Investigating further!

**Comment by rrrene** [comment]
This one should be fixed now. Can you verify?

**Comment by splattael** [comment]
It works, thank you! :fireworks:
