### ISSUE TITLE
Rebuilding a project hangs in "Running deps analysis"

### ISSUE THREAD

**Issue by splattael** [hexfaktor/hex_faktor_web#9]
Repro:
- goto https://beta.hexfaktor.org/github/splattael/sfsobject
- click on "Rebuild" button
- See "Cloning repo ..."
- See "Running deps analysis"
- ...
- nothing happens - deps won't get updated

See attached screenshot.

![screenshot from 2016-02-15 22 28 27](https://cloud.githubusercontent.com/assets/28908/13060684/7c8962a8-d433-11e5-98c2-b4219947998a.png)

**Comment by splattael** [comment]
Analysis worked before I removed `mix.lock`.

Is this file mandatory?

**Comment by rrrene** [comment]
It should not hang ... 

That said, yes, it needs `mix.lock` because otherwise we can't know what your current deps are. But you should get a message in plain-english explaining this "analysis result".

Thanks for reporting, I'll take a look! :+1:

_edit:_ english is hard ^_^
